####################################
# TRAEFIK (REVERSE PROXY)
####################################

secrets:
  cloudflare_api_token:
    file: ${DOCKER_DIRECTORY}/secrets/traefik/cloudflare_api_token.secret

services:
  traefik:
    container_name: traefik
    image: library/traefik:v3.0
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: tcp
        mode: host
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cloudflare_api_token
      DOMAIN_NAME: ${DOMAIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      LETS_ENCRYPT_ENV: ${LETS_ENCRYPT_ENV:-https://acme-v02.api.letsencrypt.org/directory}
    secrets:
      - source: cloudflare_api_token
        target: /run/secrets/cloudflare_api_token
    volumes:
      # Provision script
      - ./provision.sh:/provision.sh:ro
      # Static config
      - ./traefik.yml:/traefik.template.yml:ro
      # Rules config (dynamic)
      - ./rules:/rules:ro
      # App Data
      - /volume/traefik/logs:/logs
      - /volume/traefik/etc:/etc/traefik
      - /volume/traefik/acme/acme.json:/acme.json
    networks:
      traefik:
      docker:
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - socket-proxy
    entrypoint: []
    command: 'sh -c "/provision.sh && traefik"'
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`${TRAEFIK_SUBDOMAIN:-traefik}.${DOMAIN_NAME}`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 2375:2375
    networks:
      docker:
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      - LOG_LEVEL=notice # debug, info, notice, warning, err, crit, alert, emerg
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=1
      - DELETE=1
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1
networks:
  traefik:
    external: true
  docker:
    external: true
