####################################
# HOMEPAGE
####################################

secrets:
  openweather_api_key:
    file: ${DOCKER_DIRECTORY}/secrets/homepage/openweather.secret

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    profiles: ["utilities", "all"]
    volumes:
      - ${DOCKER_DIRECTORY}/apps/homepage/config:/config
      - ${DOCKER_DIRECTORY}/apps/homepage/icons:/app/public/icons
    environment:
      PUID: $PUID
      PGID: $PGID
      LOG_LEVEL: debug
      HOMEPAGE_FILE_OPENWEATHER_API_KEY_FILE: /run/secrets/openweather_api_key
      HOMEPAGE_ALLOWED_HOSTS: lab.wool.homes
    secrets:
      - source: openweather_api_key
        target: /run/secrets/openweather_api_key
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
      docker:
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`${DOMAIN_NAME}`)
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.service: homepage
      traefik.http.services.homepage.loadbalancer.server.port: 3000
