####################################
# HOMEPAGE
####################################

secrets:
  openweather_api_key:
    file: ${DOCKER_DIRECTORY}/secrets/homepage/openweather.secret
  homeassistant_api_key:
    file: ${DOCKER_DIRECTORY}/secrets/homepage/homeassistant.secret
  proxmox_api_key:
    file: ${DOCKER_DIRECTORY}/secrets/homepage/proxmox.secret
  jellyfin_api_key:
    file: ${DOCKER_DIRECTORY}/secrets/homepage/jellyfin.secret
  jellyseerr_api_key:
    file: ${DOCKER_DIRECTORY}/secrets/homepage/jellyseerr.secret



services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    profiles: ["utilities", "all"]
    volumes:
      - ${DOCKER_DIRECTORY}/apps/homepage/config:/config
      - ${DOCKER_DIRECTORY}/apps/homepage/icons:/app/public/icons
    environment:
      PUID: $PUID
      PGID: $PGID
      LOG_LEVEL: debug
      HOMEPAGE_FILE_OPENWEATHER_API_KEY_FILE: /run/secrets/openweather_api_key
      HOMEPAGE_FILE_HOMEASSISTANT_API_KEY_FILE: /run/secrets/homeassistant_api_key
      HOMEPAGE_FILE_PROXMOX_API_KEY_FILE: /run/secrets/proxmox_api_key
      HOMEPAGE_FILE_JELLYFIN_API_KEY_FILE: /run/secrets/jellyfin_api_key
      HOMEPAGE_FILE_JELLYSEERR_API_KEY_FILE: /run/secrets/jellyseerr_api_key
    secrets:
      - source: openweather_api_key
        target: /run/secrets/openweather_api_key
      - source: homeassistant_api_key
        target: /run/secrets/homeassistant_api_key
      - source: proxmox_api_key
        target: /run/secrets/proxmox_api_key
      - source: jellyfin_api_key
        target: /run/secrets/jellyfin_api_key
      - source: jellyseerr_api_key
        target: /run/secrets/jellyseerr_api_key
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
      docker:
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`${DOMAIN_NAME}`)
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.service: homepage
      traefik.http.services.homepage.loadbalancer.server.port: 3000
