#######################################
# PROWLARR
#######################################

services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    profiles: ["prowlarr", "arr", "all"]
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Etc/UTC
    volumes:
      - /volume/prowlarr:/config
      - /data:/data
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.${DOMAIN_NAME}`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696