################################################################################
# HOMELAB
################################################################################

include:
    #############################################################################
    # TRAEFIK (CORE)
    #############################################################################

  - apps/traefik/compose.yml # Traefik (Reverse Proxy)
  - apps/socket-proxy/compose.yml # Docker Socket Proxy (Security)


################################################################################
# NETWORK CONFIGURATION
################################################################################

networks:
    traefik:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.254.0/24
    docker:
        driver: bridge
        ipam:
            config:
                - subnet: 172.15.0.0/16
    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16