####################################################################################
# HOMELAB
####################################################################################

include:
  ################################################################################
  # TRAEFIK (INFRA)
  ################################################################################
  - apps/traefik/compose.yml # Traefik (Reverse Proxy)
  - apps/socket-proxy/compose.yml # Docker Socket Proxy (Security)

  ################################################################################
  # CORE
  ################################################################################
  - apps/homepage/compose.yml # Homepage (It's a homepage...)
  - apps/komodo/compose.yml

  ################################################################################
  # UTILITIES
  ################################################################################
  - apps/dozzle/compose.yml #  Dozzle (Container Logs)
  # - apps/monitoring/compose.yml #  Grafana, Prometheus, InfluxDB, etc.
  - apps/it-tools/compose.yml #  IT Tools (Miscellaneous)

  ################################################################################
  # APPS
  ################################################################################
  - apps/lube-logger/compose.yml #  Lube Logger (Vehicle Maintenance)
  - apps/part-db/compose.yml #  Part DB (Component Inventory)
  - apps/fasten/compose.yml #  Fasten (Personal Health Records)
  - apps/forgejo/compose.yml # Forgejo (Git)
  - apps/zipline/compose.yml # Zipline (File Sharing)
  - apps/pdf/compose.yml # Stirling PDF (PDF Tools)
  - apps/penpot/compose.yml # Penpot (Design)
  - apps/freshrss/compose.yml # FreshRSS (News Feed Reader)
  - apps/hoarder/compose.yml # Hoarder
  - apps/your-spotify/compose.yml # Your Spotify
  - apps/midpoint/compose.yml # Midpoint

####################################################################################
# NETWORK CONFIGURATION
####################################################################################

networks:
  traefik:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  docker:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24
