####################################################################################
# HOMELAB
####################################################################################

include:
    ################################################################################
    # TRAEFIK (CORE)
    ################################################################################

    - apps/traefik/compose.yml # Traefik (Reverse Proxy)
    - apps/socket-proxy/compose.yml # Docker Socket Proxy (Security)

    ################################################################################
    # SHARED
    ################################################################################
    - apps/postgres/compose.yml # Postgresql (Database)
    - apps/mariadb/compose.yml # MariaDB (Database)

    ################################################################################
    # UTILITIES
    ################################################################################
    - apps/watchtower/compose.yml #  Watchtower (Container Updating)


####################################################################################
# NETWORK CONFIGURATION
####################################################################################

networks:
    traefik:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.254.0/24
    docker:
        driver: bridge
        ipam:
            config:
                - subnet: 172.15.0.0/16
    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16