####################################################################################
# HOMELAB
####################################################################################

include:
  ################################################################################
  # TRAEFIK (INFRA)
  ################################################################################
  - apps/traefik/compose.yml # Traefik (Reverse Proxy)
  - apps/socket-proxy/compose.yml # Docker Socket Proxy (Security)

  ################################################################################
  # CORE
  ################################################################################
  - apps/homepage/compose.yml # Homepage (It's a homepage...)

  ################################################################################
  # UTILITIES
  ################################################################################
  - apps/watchtower/compose.yml #  Watchtower (Container Updating)
  - apps/dozzle/compose.yml #  Dozzle (Container Logs)
  - apps/monitoring/compose.yml #  Grafana, Prometheus, InfluxDB, etc.

  ################################################################################
  # APPS
  ################################################################################
  - apps/lube-logger/compose.yml #  Lube Logger (Vehicle Maintenance)
  - apps/changedetection/compose.yml #  Change Detection (Detecting Changes)
  - apps/part-db/compose.yml
  - apps/jupyter/compose.yml

####################################################################################
# NETWORK CONFIGURATION
####################################################################################

networks:
  traefik:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  docker:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24