####################################################################################
# HOMELAB
####################################################################################

include:
  ################################################################################
  # TRAEFIK (INFRA)
  ################################################################################
  - apps/traefik/compose.yml # Traefik (Reverse Proxy)
  - apps/socket-proxy/compose.yml # Docker Socket Proxy (Security)

  ################################################################################
  # CORE
  ################################################################################
  - apps/homepage/compose.yml # Homepage (It's a homepage...)
  - apps/authentik/compose.yml # Authentik (Central Authentication)

  ################################################################################
  # UTILITIES
  ################################################################################
  - apps/watchtower/compose.yml #  Watchtower (Container Updating)
  - apps/dozzle/compose.yml #  Dozzle (Container Logs)
  - apps/monitoring/compose.yml #  Grafana, Prometheus, InfluxDB, etc.

  ################################################################################
  # APPS
  ################################################################################
  - apps/lube-logger/compose.yml #  Lube Logger (Vehicle Maintenance)
  - apps/part-db/compose.yml #  Part DB (Component Inventory)
  - apps/changedetection/compose.yml #  Change Detection (Detecting Changes)
  - apps/jupyter/compose.yml #  Jupyter Lab (Interactive Development Environment)
  - apps/fasten/compose.yml #  Fasten (Personal Health Records)
  - apps/forgejo/compose.yml # Forgejo (Git)
  - apps/etherpad/compose.yml # Etherpad
  - apps/syncthing/compose.yml # Syncthing
  - apps/ghost/compose.yml # Ghost
####################################################################################
# NETWORK CONFIGURATION
####################################################################################

networks:
  traefik:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  docker:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24
