####################################################################################
# NEXTCLOUD
####################################################################################

services:
  nextcloud-db:
    image: postgres:15-alpine
    container_name: nextcloud-db
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    profiles: ["all", "apps", "nextcloud"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DOCKER_DIRECTORY}/appdata/nextcloud/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-nextcloud}
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-nextcloud}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      nextcloud:

  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    profiles: ["all", "apps", "nextcloud"]
    environment:
      password: ${COLLABORA_PASSWORD-collabora}
      username: ${COLLABORA_USERNAME-collabora}
      aliasgroup1: https://${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${DOMAIN_NAME}:443
      aliasgroup2: https://${COLLABORA_SUBDOMAIN:-collabora}.${DOMAIN_NAME}:443
      server_name: ${COLLABORA_SUBDOMAIN:-collabora}.${DOMAIN_NAME}
      extra_params: --o:ssl.enable:true
    labels:
      traefik.enable: true
      traefik.http.routers.collabora.rule: Host(`${COLLABORA_SUBDOMAIN:-collabora}.${DOMAIN_NAME}`)
      traefik.http.routers.collabora.entrypoints: websecure
      traefik.http.routers.collabora.service: collabora
      traefik.http.services.collabora.loadbalancer.server.port: 9980

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    networks:
      nextcloud:
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    profiles: ["all", "apps", "nextcloud"]
    command: redis-server --requirepass

  nextcloud-app:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud-app
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_started
    profiles: ["all", "apps", "nextcloud"]
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      # REDIS_HOST: nextcloud-redis:6379
      POSTGRES_DB: ${POSTGRES_DB-nextcloud}
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-nextcloud}
      POSTGRES_HOST: nextcloud-db
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${DOMAIN_NAME}
      NEXTCLOUD_UPDATE: 1
      NEXTCLOUD_DATA_DIR: /media/nextcloud
    volumes:
      - ${DOCKER_DIRECTORY}/apps/nextcloud/config:/config
      - /media/nextcloud:/data
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: Host(`${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${DOMAIN_NAME}`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      traefik.http.routers.nextcloud.middlewares: "nextcloud-dav"
      traefik.http.middlewares.nextcloud-dav.replacepathregex.regex: "^/.well-known/ca(l|rd)dav"
      traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement: "/remote.php/dav/"

      homepage.group: Apps
      homepage.name: NextCloud
      homepage.icon: nextcloud.svg
      homepage.href: https://${NEXTCLOUD_SUBDOMAIN:-nextcloud}.${DOMAIN_NAME}
      homepage.description: "The cloud™"
    networks:
      traefik:
      nextcloud:

  nextcloud-cron:
    image: nextcloud:latest
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    profiles: ["all", "apps", "nextcloud"]
    volumes:
      - ${DOCKER_DIRECTORY}/apps/nextcloud/config:/config
      - /media/nextcloud:/data
    entrypoint: /cron.sh
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_started
    networks:
      nextcloud:

networks:
  nextcloud:
    external: false
