#######################################
# HOARDER
#######################################

services:
  karakeep-web:
    container_name: karakeep-web
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    profiles: ['karakeep', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/karakeep/web:/data
    networks:
      traefik:
      karakeep:
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.karakeep.rule: Host(`${KARAKEEP_SUBDOMAIN:-karakeep}.${DOMAIN_NAME}`)
      traefik.http.routers.karakeep.entrypoints: websecure
      traefik.http.routers.karakeep.service: karakeep
      traefik.http.services.karakeep.loadbalancer.server.port: 3000

      homepage.group: Apps
      homepage.name: karakeep
      homepage.icon: karakeep.svg
      homepage.href: https://${KARAKEEP_SUBDOMAIN:-karakeep}.${DOMAIN_NAME}
      homepage.description: The bookmark everything app
  chrome:
    container_name: karakeep-chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    profiles: ['karakeep', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    env_file:
      - .env
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      karakeep:
  meilisearch:
    container_name: karakeep-search
    image: getmeili/meilisearch:v1.11.1
    profiles: ['karakeep', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      karakeep:
    environment:
      MEILI_NO_ANALYTICS: "true"
    env_file:
      - .env
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/karakeep/search:/data

networks:
  karakeep:
    external: false
