services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    profiles: ['monitoring', 'all']
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
      DOCKER_HOST: tcp://socket-proxy:2375
    secrets:
      - source: 
        target: /run/secrets/
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/dozzle:/
    security_opt:
      - no-new-privileges:true
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
      docker:
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.rule: Host(`${DOZZLE_SUBDOMAIN:-dozzle}.${DOMAIN_NAME}`)
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.routers.dozzle.service: dozzle
      traefik.http.services.dozzle.loadbalancer.server.port: 8080


      
      
      