include:
  - socket-proxy.yml
  - traefik/compose.yml
  - sabnzbd/compose.yml
  - prowlarr/compose.yml
  - sonarr/compose.yml
  - radarr/compose.yml
  - readarr/compose.yml
  - jellyfin/compose.yml
  - jellyseerr/compose.yml
  - autoscan/compose.yml

networks:
  traefik:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  docker:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24
