include:
  - socket-proxy.yml
  - traefik/compose.yml
  - sabnzbd/compose.yml
  - prowlarr/compose.yml
  - sonarr/compose.yml
  - radarr/compose.yml
  - readarr/compose.yml
  - jellyfin/compose.yml
  - jellyseerr/compose.yml
  - autoscan/compose.yml

networks:
  proxy:
  docker:
