#######################################
# READARR
#######################################

services:
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/radarr
    profiles: ["readarr", "arr", "all"]
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Etc/UTC
    volumes:
      - /volume/readarr:/config
      - /data:/data
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.readarr.rule: Host(`readarr.${DOMAIN_NAME}`)
      traefik.http.routers.readarr.entrypoints: websecure
      traefik.http.routers.readarr.service: readarr
      traefik.http.services.readarr.loadbalancer.server.port: 8787