#######################################
# JELLYSEERR
#######################################

services:
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    profiles: ["jellyseerr", "arr", "all"]
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Etc/UTC
    volumes:
      - /volume/jellyseerr:/config
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.${DOMAIN_NAME}`)
      traefik.http.routers.jellyseerr.entrypoints: websecure
      traefik.http.routers.jellyseerr.service: jellyseerr
      traefik.http.services.jellyseerr.loadbalancer.server.port: 5055