---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Work:
  - SeaPort:
    - icon: https://seaport.seaworldentertainment.com/client/images/apple-touch-icon-precomposed.png
      href: https://seaport.seaworldentertainment.com/client/mytoday
      description: Schedules and Company News
  - ReadyOp:
    - icon: https://seaworld.readyop.com/assets/images/icons/apple-touch-icon.png
      href: https://seaworld.readyop.com/
      description: Security Logs and Reports
  - Job Postings:
    - icon: mdi-briefcase-search
      href: https://www.myworkday.com/seaworldentertainment/d/task/3005$4482.htmld
      description: Open Job Postings
  - Workday:
    - icon: https://user-images.githubusercontent.com/13351305/162011104-9b313d6a-1b19-45fd-9237-2de5c73182b6.svg
      href: https://www.myworkday.com/seaworldentertainment/d/home.htmld
      description: Time Keeping and Business Processes

- Personal:
  - YouTube:
    - icon: youtube.svg
      href: https://youtube.com
      description:
  - Proton Mail:
    - icon: proton-mail.svg
      href: https://mail.proton.me/u/0/inbox
      description:
  - Amazon:
    - icon: si-amazon
      href: https://amazon.com/gp/css/order-history
      description:

- School:
  - Canvas:
    - icon: si-canvas
      href: https://hcc.instructure.com/
  - Email:
    - icon: microsoft-outlook.svg
      href: https://outlook.com/owa/hccfl.edu
  - MyHCC:
    - icon: mdi-school
      href: https://my.hccfl.edu/
  - OneDrive:
    - icon: microsoft-onedrive.svg
      href: https://hccfl-my.sharepoint.com/my      

- Developer:
  - Github:
    - icon: github.svg
      href: https://github.com/esize?tab=repositories
  - Simple Icons:
    - icon: si-simpleicons
      href: https://simpleicons.org/
  - Dashboard Icons:
    - icon: mdi-view-dashboard
      href: https://github.com/walkxcode/dashboard-icons/tree/main/svg
  - MDI:
    - icon: mdi-vector-square
      href: https://pictogrammers.com/library/mdi/