---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

my-docker:
  host: socket-proxy
  port: 2375

# my-docker:
#   socket: /var/run/docker.sock
