---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Smart Home:
    - Home Assistant:
        href: https://home.wool.homes/
        description: Smart Home hub
        icon: si-homeassistant
        siteMonitor: https://home.wool.homes/
        widget:
          type: homeassistant
          url: https://home.wool.homes/
          key: {{ HOMEPAGE_FILE_HOMEASSISTANT_API_KEY_FILE }}
    - ESPHome:
        href: https://home.wool.homes/5c53de3b_esphome/ingress
        description: Turn microcontrollers into IOT devices
        icon: si-esphome
        siteMonitor: https://home.wool.homes/5c53de3b_esphome/ingress
        widget:
          type: esphome
          url: http://192.168.254.172:6052

- Infra:
    - Proxmox:
        href: https://proxmox.lab.wool.homes/
        description: Enterprise Virtualization Platform
        icon: si-proxmox
        siteMonitor: https://proxmox.lab.wool.homes/
    - Proxmox Backup Server:
        href: https://pbs.lab.wool.homes/
        description: Enterprise Backup Platform
        icon: mdi-backup-restore
        siteMonitor: https://pbs.lab.wool.homes/
    - PiHole:
        href: http://pi.hole/admin/login.php/
        description: Ad Blocking and Local DNS
        icon: si-pihole
        siteMonitor: http://pi.hole/admin/

- Media:
    - Jellyfin:
        href: https://jellyfin.media.wool.homes/
        description: Self-hosted streaming service
        icon: si-jellyfin
        siteMonitor: https://jellyfin.media.wool.homes/
    - Jellyseerr:
        href: https://jellyseerr.media.wool.homes/
        description: Media request management
        icon: jellyseerr.svg
        siteMonitor: https://jellyseerr.media.wool.homes/
    - Radarr:
        href: https://radarr.media.wool.homes/
        description: Movie manager and automation
        icon: si-radarr
        siteMonitor: https://radarr.media.wool.homes/
    - Sonarr:
        href: https://sonarr.media.wool.homes/
        description: TV show manager and automation
        icon: si-sonarr
        siteMonitor: https://sonarr.media.wool.homes/
    - Readarr:
        href: https://readarr.media.wool.homes/
        description: Book manager and automation
        icon: readarr.svg
        siteMonitor: https://readarr.media.wool.homes/
    - Bazarr:
        href: https://bazarr.media.wool.homes/
        description: Subtitle management
        icon: bazarr.svg
        siteMonitor: https://bazarr.media.wool.homes/
    - Prowlarr:
        href: https://prowlarr.media.wool.homes/
        description: Indexer management
        icon: prowlarr.svg
        siteMonitor: https://prowlarr.media.wool.homes/
    - SABnzbd:
        href: https://sabnzbd.media.wool.homes/
        description: Usenet Client
        icon: sabnzbd.svg
        siteMonitor: https://sabnzbd.media.wool.homes/
    - SABnzbd:
        href: https://qbittorrent.media.wool.homes/
        description: Torrent Client
        icon: qbittorrent.svg
        siteMonitor: https://qbittorrent.media.wool.homes/