---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Smart Home:
    - Home Assistant:
        href: https://home.wool.homes/
        description: Smart Home hub
        icon: si-homeassistant
        siteMonitor: https://home.wool.homes/
        widget:
          type: homeassistant
          url: https://home.wool.homes/
          key: {{ HOMEPAGE_FILE_HOMEASSISTANT_API_KEY_FILE }}
          fields:
            - lights_on
            - switches_on
    - ESPHome:
        href: https://home.wool.homes/5c53de3b_esphome/ingress
        description: Turn microcontrollers into IOT devices
        icon: si-esphome
        siteMonitor: https://home.wool.homes/5c53de3b_esphome/ingress
        widget:
          type: esphome
          url: http://192.168.254.172:6052

- Infra:
    - Proxmox:
        href: https://proxmox.lab.wool.homes/
        description: Enterprise Virtualization Platform
        icon: si-proxmox
        siteMonitor: https://proxmox.lab.wool.homes/
    - Proxmox Backup Server:
        href: https://pbs.lab.wool.homes/
        description: Enterprise Backup Platform
        icon: mdi-backup-restore
        siteMonitor: https://pbs.lab.wool.homes/
    - PiHole:
        href: http://pi.hole/admin/login.php/
        description: Ad Blocking and Local DNS
        icon: si-pihole
        siteMonitor: http://pi.hole/admin/

- Media:
    - Jellyfin:
        href: https://jellyfin.media.wool.homes/
        description: Self-hosted streaming service
        icon: si-jellyfin
        siteMonitor: https://jellyfin.media.wool.homes/
        widget:
          type: jellyfin
          url: https://jellyfin.media.wool.homes/
          key: {{ HOMEPAGE_FILE_JELLYFIN_API_KEY_FILE }}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Jellyseerr:
        href: https://jellyseerr.media.wool.homes/
        description: Media request management
        icon: jellyseerr.svg
        siteMonitor: https://jellyseerr.media.wool.homes/
        widget:
            type: jellyseerr
            url: https://jellyseerr.media.wool.homes
            key: {{ HOMEPAGE_FILE_JELLYSEERR_API_KEY_FILE }}
    - Radarr:
        href: https://radarr.media.wool.homes/
        description: Movie manager and automation
        icon: si-radarr
        siteMonitor: https://radarr.media.wool.homes/
        widget:
            type: radarr
            url: https://radarr.media.wool.homes
            key: {{ HOMEPAGE_FILE_RADARR_API_KEY_FILE }}
            enableQueue: true
    - Sonarr:
        href: https://sonarr.media.wool.homes/
        description: TV show manager and automation
        icon: si-sonarr
        siteMonitor: https://sonarr.media.wool.homes/
        widget:
            type: sonarr
            url: https://sonarr.media.wool.homes
            key: {{ HOMEPAGE_FILE_SONARR_API_KEY_FILE }}
            enableQueue: true # optional, defaults to false
    - Readarr:
        href: https://readarr.media.wool.homes/
        description: Book manager and automation
        icon: readarr.svg
        siteMonitor: https://readarr.media.wool.homes/
        widget:
            type: readarr
            url: https://readarr.media.wool.homes
            key: {{ HOMEPAGE_FILE_READARR_API_KEY_FILE }}
    - Prowlarr:
        href: https://prowlarr.media.wool.homes/
        description: Indexer management
        icon: prowlarr.svg
        siteMonitor: https://prowlarr.media.wool.homes/
        widget:
            type: prowlarr
            url: https://prowlarr.media.wool.homes
            key: {{ HOMEPAGE_FILE_PROWLARR_API_KEY_FILE }}
    - SABnzbd:
        href: https://sabnzbd.media.wool.homes/
        description: Usenet Client
        icon: sabnzbd.svg
        siteMonitor: https://sabnzbd.media.wool.homes/
        widget:
            type: sabnzbd
            url: https://sabnzbd.media.wool.homes
            key: {{ HOMEPAGE_FILE_SABNZBD_API_KEY_FILE }}