---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Smart Home:
    - Home Assistant:
        href: https://home.wool.homes/
        description: Smart Home hub
        icon: si-homeassistant
        siteMonitor: https://home.local.wool.homes/
        widget:
          type: homeassistant
          url: https://home.wool.homes/
          key: { { HOMEPAGE_FILE_HOMEASSISTANT_API_KEY_FILE } }
          fields:
            - lights_on
            - switches_on
    - ESPHome:
        href: https://home.wool.homes/5c53de3b_esphome/ingress
        description: Turn microcontrollers into IOT devices
        icon: si-esphome
        siteMonitor: https://home.wool.homes/5c53de3b_esphome/ingress
        widget:
          type: esphome
          url: http://192.168.254.172:6052

- Infra:
    - Proxmox:
        href: https://proxmox.lab.wool.homes/
        description: Enterprise Virtualization Platform
        icon: si-proxmox
        siteMonitor: https://proxmox.local.wool.homes/
    - PiHole:
        href: http://pi.hole/admin/login.php/
        description: Ad Blocking and Local DNS
        icon: si-pihole
        siteMonitor: http://pi.hole/admin/
    - Ansible Semaphore:
        href: https://ansible.local.wool.homes
        description: Ansible Semaphore dashboard and automations.
        icon: si-ansible
        siteMonitor: https://ansible.local.wool.homes

- Enterprise:
    - Business Central:
        href: https://business.local.wool.homes/business-central/
        description: Business process management
        icon: https://drools.org/headerFooter/droolsIcon.png
        siteMonitor: https://business.local.wool.homes/
    - OrangeHRM:
        href: https://hr.local.wool.homes/
        description: HR Management System
        icon: https://avatars3.githubusercontent.com/u/11557709?s=280&v=4
        siteMonitor: https://hr.local.wool.homes/
    - OpenEMR:
        href: https://openemr.local.wool.homes/
        description: Electronic Health Record System
        icon: https://www.open-emr.org/wiki/images/d/de/Menu-logo-large.png
        siteMonitor: https://openemr.local.wool.homes/
    - Keycloak:
        href: https://keycloak.local.wool.homes/
        description: LDAP
        icon: si-keycloak
        siteMonitor: https://keycloak.local.wool.homes/

- Media:
    - Jellyfin:
        href: https://jellyfin.lab.wool.homes/
        description: Self-hosted streaming service
        icon: si-jellyfin
        siteMonitor: https://jellyfin.lab.wool.homes/
        widget:
          type: jellyfin
          url: http://192.168.254.13:8096
          key: { { HOMEPAGE_FILE_JELLYFIN_API_KEY_FILE } }
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Jellyseerr:
        href: https://jellyseerr.lab.wool.homes/
        description: Media request management
        icon: jellyseerr.svg
        siteMonitor: https://jellyseerr.lab.wool.homes/
    - MakeMKV:
        href: https://makemkv.lab.wool.homes/
        description: DVD ripper
        icon: makemkv.png
        siteMonitor: https://makemkv.lab.wool.homes/
    - nzbget:
        href: https://nzbget.lab.wool.homes/
        description: Usenet NZB client
        icon: nzbget.png
        siteMonitor: https://nzbget.local.wool.homes/
    - qBittorrent:
        href: https://torrent.lab.wool.homes/
        description: Bittorrent Client
        icon: si-qbittorrent
        siteMonitor: https://torrent.lab.wool.homes/
    - Radarr:
        href: https://radarr.lab.wool.homes/
        description: Movie manager and automation
        icon: si-radarr
        siteMonitor: https://radarr.lab.wool.homes/
    - Sonarr:
        href: https://sonarr.lab.wool.homes/
        description: TV show manager and automation
        icon: si-sonarr
        siteMonitor: https://sonarr.lab.wool.homes/
    - Readarr:
        href: https://readarr.lab.wool.homes/
        description: Book manager and automation
        icon: readarr.svg
        siteMonitor: https://readarr.local.wool.homes/
    - Tdarr:
        href: https://tdarr.lab.wool.homes/
        description: Transcoding manager and automation
        icon: https://home.tdarr.io/static/media/logo3-min.246d6df44c7f16ddebaf.png
        siteMonitor: https://tdarr.lab.wool.homes/
    - Prowlarr:
        href: https://prowlarr.lab.wool.homes/
        description: Indexer management
        icon: prowlarr.svg
        siteMonitor: https://prowlarr.lab.wool.homes/
    - Calibre:
        href: https://calibre.lab.wool.homes/
        description: E-book manager and editor
        icon: si-calibreweb
        siteMonitor: https://calibre.lab.wool.homes/
