---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Weather:
    - OpenMeteo:
        description: Homepage is awesome
        widget: openmeteo

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
