---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Smart Home:
    - Home Assistant:
        href: https://home.local.wool.homes/
        description: Smart Home hub
        icon: home-assistant.svg
        siteMonitor: https://home.local.wool.homes/
        widget:
            type: homeassistant
            url: https://home.local.wool.homes/
            key: {{HOMEPAGE_FILE_HOMEASSISTANT_API_KEY_FILE}}
            fields:
                - lights_on
                - switches_on
- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
