---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Smart Home:
    - Home Assistant:
        href: https://home.local.wool.homes/
        description: Smart Home hub
        icon: si-homeassistant
        siteMonitor: https://home.local.wool.homes/
        widget:
            type: homeassistant
            url: https://home.local.wool.homes/
            key: {{HOMEPAGE_FILE_HOMEASSISTANT_API_KEY_FILE}}
            fields:
                - lights_on
                - switches_on
    - ESPHome:
        href: https://home.local.wool.homes/5c53de3b_esphome/ingress
        description: Turn microcontrollers into IOT devices
        icon: si-esphome
        siteMonitor: https://home.local.wool.homes/5c53de3b_esphome/ingress
        widget:
            type: esphome
            url: http://192.168.254.172:6052

- Dev:
    - Forgejo:
        href: https://forgejo.local.wool.homes/
        description: Self-hosted GitHub
        icon: si-forgejo
        siteMonitor: https://forgejo.local.wool.homes/
    - Penpot:
        href: https://penpot.local.wool.homes/
        description: Open Source Design and Collaboration Tool
        icon: si-penpot
        siteMonitor: https://penpot.local.wool.homes/

- Infra:
    - Proxmox:
        href: https://proxmox.local.wool.homes/
        description: Enterprise Virtualization Platform
        icon: si-proxmox
        siteMonitor: https://proxmox.local.wool.homes/
    - PiHole:
        href: http://pi.hole/admin/login.php/
        description: Ad Blocking and Local DNS
        icon: si-pihole
        siteMonitor: http://pi.hole/admin/
    - TrueNAS:
        href: https://truenas.local.wool.homes/ui/storage/
        description: NAS and some Kubernetes fun
        icon: si-truenas
        siteMonitor: http://192.168.254.5:81
    - Authentik:
        href: https://auth.local.wool.homes/if/admin/
        description: All things auth
        icon: si-authentik
        siteMonitor: https://auth.local.wool.homes
    - Ansible Semaphore:
        href: https://ansible.local.wool.homes
        description: Ansible Semaphore dashboard and automations.
        icon: si-ansible
        siteMonitor: https://ansible.local.wool.homes

- Apps:
    - Fasten Health:
        href: https://fasten.local.wool.homes
        description: Self-hosted health records
        icon: https://github.com/fastenhealth/fasten-onprem/blob/main/frontend/src/assets/favicon/android-chrome-512x512.png?raw=true
        siteMonitor: https://fasten.local.wool.homes
    - Immich:
        href: https://immich.local.wool.homes
        description: Google Photos but local
        icon: si-immich
        siteMonitor: https://immich.local.wool.homes
    - Paperless:
        href: https://paperless.local.wool.homes/
        description: Document management system
        icon: si-paperlessngx
        siteMonitor: https://paperless.local.wool.homes/
    - IT-Tools:
        href: https://tools.local.wool.homes/
        description: Handy tools for developers
        icon: it-tools.svg
        siteMonitor: https://tools.local.wool.homes/
    - Stirling PDF:
        href: https://pdf.local.wool.homes
        description: Sooooo many pdf tools!
        icon: stirling-pdf.svg
        siteMonitor: https://pdf.local.wool.homes
    - FreshRSS:
        href: https://rss.local.wool.homes
        description: Aggregate RSS feeds for easy consumption
        icon: freshrss.svg
        siteMonitor: https://rss.local.wool.homes
    - Zipline:
        href: https://zipline.local.wool.homes/
        description: Screenshots and pastebins
        icon: https://raw.githubusercontent.com/diced/zipline/trunk/public/zipline.png
        siteMonitor: https://zipline.local.wool.homes/