---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: {{HOMEPAGE_FILE_OPENWEATHER_API_KEY_FILE}}
  weatherapi: weatherapiapikey
title: WoolHomepage
background:
  image: https://images.unsplash.com/photo-1542396601-dca920ea2807?q=80&w=2702&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: md
cardBlur: lg
theme: dark
color: slate
language: en-US
target: _self
hideVersion: true
showStats: true
