---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: {{HOMEPAGE_FILE_OPENWEATHER_API_KEY_FILE}}
  weatherapi: weatherapiapikey
title: WoolHomepage
background:
  image: https://images.unsplash.com/photo-1538370965046-79c0d6907d47?q=80&w=2669&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
cardBlur: sm
theme: dark
color: slate
language: en-US
target: _self
hideVersion: true
headerStyle: boxed
showStats: false
statusStyle: basic
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
layout:
  - Work:
    style: row
    columns: 4
  - Personal:
    style: row
    columns: 3
  - Apps:
  - Docker:
  - Developer:
  - Dev:
    header: false
  - Infra:
  - Smart Home:
