---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets
- datetime:
    text_size: xl
    format:
      timeStyle: short

- search:
    provider: duckduckgo
    target: _blank
- openweathermap:
    label: Home
    latitude: 27.9475
    longitude: -82.4584
    timezone: America/New_York
    units: imperial
    provider: openweathermap
    cache: 5
    format:
        maximumFractionDigits: 1
