####################################
# TRAEFIK (REVERSE PROXY)
####################################

secrets:
  cloudflare_api_token:
    file: ${DOCKER_DIRECTORY}/secrets/traefik/cloudflare_api_token.secret
  github_oauth:
    file: ${DOCKER_DIRECTORY}/secrets/traefik/github_oauth.secret

services:
  traefik:
    container_name: traefik
    image: library/traefik:v3.0
    profiles: ["traefik", "core", "all"]
    ports:
      - published: 80
        target: 80
        protocol: tcp
        mode: host
      - published: 443
        target: 443
        protocol: tcp
        mode: host
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cloudflare_api_token
    secrets:
      - source: cloudflare_api_token
        target: /run/secrets/cloudflare_api_token
    volumes:
      # Rules config
      - ${DOCKER_DIRECTORY}/apps/traefik/rules:/rules
      # App Data
      - ${DOCKER_DIRECTORY}/appdata/traefik/logs:/logs
      - ${DOCKER_DIRECTORY}/appdata/traefik/traefik:/etc/traefik
      - ${DOCKER_DIRECTORY}/appdata/traefik/acme/acme.json:/acme.json
    networks:
      traefik:
      docker:
    security_opt:
      - no-new-privileges:true
    restart: always
    depends_on:
      - socket-proxy
      - traefik-forward-auth
    command:
      # GLOBAL SETTINGS
      - --global.checkNewVersion=true
      # API SETTINGS
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      # LOGGING SETTINGS
      - --log=true
      - --log.level=INFO # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=204-299,400-499,500-599
      # PROVIDERS
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=homelab_traefik
      # - --providers.docker.tls.insecureSkipVerify=true
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      # ENTRYPOINTS
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.http.tls.certresolver=dns-cloudflare
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN_NAME}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN_NAME}
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.options=tls-opts@file
      - --entrypoints.websecure.http.tls.options=tls-opts@file
      # CERTIFICATE RESOLVER
      - --certificatesResolvers.dns-cloudflare.acme.caServer=${LETS_ENCRYPT_ENV:-https://acme-v02.api.letsencrypt.org/directory}
      - --certificatesResolvers.dns-cloudflare.acme.email=${ADMIN_EMAIL}
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`${TRAEFIK_SUBDOMAIN:-traefik}.${DOMAIN_NAME}`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal
      # traefik.http.routers.traefik.middlewares: chain-oauth-github@file

  traefik-forward-auth:
    container_name: traefik-forward-auth
    image: thomseddon/traefik-forward-auth:2
    profiles: ["traefik", "core", "all"]
    environment:
      CONFIG: /config
      COOKIE_DOMAIN: ${DOMAIN_NAME}
      INSECURE_COOKIE: "false"
      AUTH_HOST: ${AUTH_SUBDOMAIN:-traefik-forward-auth}.${DOMAIN_NAME}
      URL_PATH: /_oauth
      LOG_LEVEL: debug
      LIFETIME: 2592000
      DEFAULT_ACTION: auth
      DEFAULT_PROVIDER: "generic_oauth"
    secrets:
      - source: github_oauth
        target: /config
    networks:
      traefik:
      internal:
    security_opt:
      - no-new-privileges:true
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "<Successful command here>"
        ]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
    labels:
      traefik.enable: true
      traefik.http.routers.traefik-forward-auth.rule: Host(`${AUTH_SUBDOMAIN:-traefik-forward-auth}.${DOMAIN_NAME}`)
      traefik.http.routers.traefik-forward-auth.entrypoints: websecure
      traefik.http.routers.traefik-forward-auth.service: traefik-forward-auth
      traefik.http.services.traefik-forward-auth.loadbalancer.server.port: 4181
      traefik.http.routers.traefik-forward-auth.middlewares: chain-oauth-github@file