global:
  checkNewVersion: true

api:
  dashboard: true
  insecure: true

log:
  level: INFO

accessLog:
  filePath: /logs/access.log
  bufferingSize: 100
  filters:
    statusCodes: "204-299,400-499,500-599"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: homelab_traefik
  file:
    directory: /rules
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: dns-cloudflare
        domains:
          - main: ${DOMAIN_NAME}
            sans:
              - "*.${DOMAIN_NAME}"
        options: tls-opts@file

certificatesResolvers:
  dns-cloudflare:
    acme:
      caServer: ${LE_ENV}
      email: ${ADMIN_EMAIL}
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: 90