services:
  midpoint_data:
    image: postgres:16-alpine
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    environment:
     - POSTGRES_PASSWORD=db.secret.pw.007
     - POSTGRES_USER=midpoint
     - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    networks:
     - net
    volumes:
     - ${DOCKER_DIRECTORY}/appdata/midpoint/db:/var/lib/postgresql/data
  data_init:
    image: evolveum/midpoint:${MP_VER:-latest}-alpine
    command: >
      bash -c "
      cd /opt/midpoint ;
      bin/midpoint.sh init-native ;
      echo ' - - - - - - ' ;
      bin/ninja.sh -B info >/dev/null 2>/tmp/ninja.log ;
      grep -q \"ERROR\" /tmp/ninja.log && (
      bin/ninja.sh run-sql --create --mode REPOSITORY  ;
      bin/ninja.sh run-sql --create --mode AUDIT
      ) ||
      echo -e '\\n Repository init is not needed...' ;
      "
    depends_on:
     - midpoint_data
    environment:
     - PUID=1000
     - PGID=1000
     - MP_SET_midpoint_repository_jdbcUsername=midpoint
     - MP_SET_midpoint_repository_jdbcPassword=db.secret.pw.007
     - MP_SET_midpoint_repository_jdbcUrl=jdbc:postgresql://midpoint_data:5432/midpoint
     - MP_SET_midpoint_repository_database=postgresql
     - MP_INIT_CFG=/opt/midpoint/var
    networks:
     - net
    volumes:
     - ${DOCKER_DIRECTORY}/appdata/midpoint/home:/opt/midpoint/var
    user: "1000:1000"

  midpoint_server:
    image: evolveum/midpoint:${MP_VER:-latest}-alpine
    depends_on:
      data_init:
        condition: service_completed_successfully
      midpoint_data:
        condition: service_started
    command: [ "/opt/midpoint/bin/midpoint.sh", "container" ]
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    environment:
     - PUID=1000
     - PGID=1000
     - MP_SET_midpoint_repository_jdbcUsername=midpoint
     - MP_SET_midpoint_repository_jdbcPassword=db.secret.pw.007
     - MP_SET_midpoint_repository_jdbcUrl=jdbc:postgresql://midpoint_data:5432/midpoint
     - MP_SET_midpoint_repository_database=postgresql
     - MP_SET_midpoint_administrator_initialPassword=Test5ecr3t
     - MP_UNSET_midpoint_repository_hibernateHbm2ddl=1
     - MP_NO_ENV_COMPAT=1
    networks:
     - net
     - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.midpoint.rule: Host(`${MIDPOIONT_SUBDOMAIN:-midpoint}.${DOMAIN_NAME}`)
      traefik.http.routers.midpoint.entrypoints: websecure
      traefik.http.routers.midpoint.service: midpoint
      traefik.http.services.midpoint.loadbalancer.server.port: 8080

      homepage.group: Apps
      homepage.name: Midpoint
      homepage.icon: midpoint.png
      homepage.href: https://${MIDPOIONT_SUBDOMAIN:-midpoint}.${DOMAIN_NAME}
      homepage.description: Authorization
    volumes:
     - ${DOCKER_DIRECTORY}/appdata/midpoint/home:/opt/midpoint/var
    user: "1000:1000"

networks:
  net:
