################################################################################
# YOUR SPOTIFY
################################################################################

services:
  server:
    container_name: your-spotify-server
    image: yooooomi/your_spotify_server
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}

    environment:
      API_ENDPOINT: https://${YOUR_SPOTIFY_SERVER_SUBDOMAIN:-your-spotify-server}.${DOMAIN_NAME} # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://${YOUR_SPOTIFY_SUBDOMAIN:-music-history}.${DOMAIN_NAME}
      LOG_LEVEL: debug
      TIMEZONE: America/New_York
    networks:
      internal:
      traefik:
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.your-spotify-server.rule: Host(`${YOUR_SPOTIFY_SERVER_SUBDOMAIN:-your-spotify-server}.${DOMAIN_NAME}`)
      traefik.http.routers.your-spotify-server.entrypoints: websecure
      traefik.http.routers.your-spotify-server.service: your-spotify-server
      traefik.http.services.your-spotify-server.loadbalancer.server.port: 8080
    
  mongo:
    container_name: mongo
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    image: mongo:4.4
    networks:
      internal:
    volumes:
      -  ${DOCKER_DIRECTORY}/appdata/your-spotify:/data/db

  web:
    container_name: your-spotify-web
    image: yooooomi/your_spotify_client
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    # Port 3000
    networks:
      traefik:
      internal:
    environment:
      API_ENDPOINT: ${YOUR_SPOTIFY_SERVER_SUBDOMAIN:-your-spotify-server}.${DOMAIN_NAME} # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://${YOUR_SPOTIFY_SUBDOMAIN:-music-history}.${DOMAIN_NAME}
      LOG_LEVEL: debug
      TIMEZONE: America/New_York
    labels:
      traefik.enable: true
      traefik.http.routers.music-history.rule: Host(`${YOUR_SPOTIFY_SUBDOMAIN:-music-history}.${DOMAIN_NAME}`)
      traefik.http.routers.music-history.entrypoints: websecure
      traefik.http.routers.music-history.service: music-history
      traefik.http.services.music-history.loadbalancer.server.port: 3000

      homepage.group: Apps
      homepage.name: Your Spotify
      homepage.icon: si-spotify
      homepage.href: https://${YOUR_SPOTIFY_SUBDOMAIN:-music-history}.${DOMAIN_NAME}
      homepage.description: Self hosted Spotify tracking dashboard