services:
  ghost:
    image: ghost
    profiles: ["all", "apps", "ghost"]
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/ghost/content:/var/lib/ghost/content
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    container_name: ghost
    environment:
      database__client: mysql
      database__connection__host: ghostdb
      database__connection__user: mariadbuser
      database__connection__password: mariadbpassword
      database__connection__database: ghost
      url: https://${GHOST_SUBDOMAIN:-ghost}.${DOMAIN_NAME}

    labels:
      traefik.enable: true
      traefik.http.routers.ghost.rule: Host(`${GHOST_SUBDOMAIN:-ghost}.${DOMAIN_NAME}`)
      traefik.http.routers.ghost.entrypoints: websecure
      traefik.http.routers.ghost.service: ghost
      traefik.http.services.ghost.loadbalancer.server.port: 2368
    depends_on:
      - ghostdb
    networks:
      - ghost
      - traefik

  ghostdb:
    image: mariadb:10.5.3
    container_name: ghostdb
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/ghost/db:/var/lib/mysql
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: ghost
      MYSQL_USER: mariadbuser
      MYSQL_PASSWORD: mariadbpassword
    networks:
      - ghost


networks:
  ghost: