#######################################
# HOARDER
#######################################

services:
  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    profiles: ['hoarder', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/hoarder/web:/data
    networks:
      traefik:
      hoarder:
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    profiles: ['hoarder', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      hoarder:
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    profiles: ['hoarder', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/hoarder/search:/data

