#######################################
# HOARDER
#######################################

services:
  hoarder-web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    profiles: ['hoarder', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/hoarder/web:/data
    networks:
      traefik:
      hoarder:
    environment:
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: super_secret_string
      NEXTAUTH_URL: https://${HOARDER_SUBDOMAIN:-hoarder}.${DOMAIN_NAME}
      MEILI_MASTER_KEY: strong_secret
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
    labels:
      traefik.enable: true
      traefik.http.routers.hoarder.rule: Host(`${HOARDER_SUBDOMAIN:-hoarder}.${DOMAIN_NAME}`)
      traefik.http.routers.hoarder.entrypoints: websecure
      traefik.http.routers.hoarder.service: hoarder
      traefik.http.services.hoarder.loadbalancer.server.port: 3000

      homepage.group: Apps
      homepage.name: Hoarder
      homepage.icon: hoarder.svg
      homepage.href: https://${HOARDER_SUBDOMAIN:-hoarder}.${DOMAIN_NAME}
      homepage.description: The bookmark everything app
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    profiles: ['hoarder', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    environment:
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: super_secret_string
      NEXTAUTH_URL: https://${HOARDER_SUBDOMAIN:-hoarder}.${DOMAIN_NAME}
      MEILI_MASTER_KEY: strong_secret
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      hoarder:
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    profiles: ['hoarder', 'apps', 'all']
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      hoarder:
    environment:
      MEILI_NO_ANALYTICS: "true"
      HOARDER_VERSION: release
      NEXTAUTH_SECRET: super_secret_string
      NEXTAUTH_URL: https://${HOARDER_SUBDOMAIN:-hoarder}.${DOMAIN_NAME}
      MEILI_MASTER_KEY: strong_secret
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/hoarder/search:/data

networks:
  hoarder:
    external: false
