################################################################################
# IT TOOLS
################################################################################

services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools:latest
    profiles: ["utilities", "all"]
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.tools.rule: Host(`${IT_TOOLS_SUBDOMAIN:-tools}.${DOMAIN_NAME}`)
      traefik.http.routers.tools.entrypoints: websecure
      traefik.http.routers.tools.service: tools
      traefik.http.services.tools.loadbalancer.server.port: 80

      homepage.group: Apps
      homepage.name: IT Tools
      homepage.icon: it-tools.svg
      homepage.href: https://${IT_TOOLS_SUBDOMAIN:-tools}.${DOMAIN_NAME}
      homepage.description: Miscellaneous IT Tools
