################################################################################
# ZIPELINE (FILE SHARING)
################################################################################

services:
  zipline:
    container_name: zipline
    image: ghcr.io/diced/zipline
    profiles: ["zipline", "apps", "all"]
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
      zipline:
    environment:
      - CORE_RETURN_HTTPS=true
      - CORE_SECRET=RMbcIzuRhDAFzXE0awfdG6WrlUPL1pEs0bVHVFkdEAOeflAEH4XIhqXtsJVuZkIa
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - CORE_LOGGER=true
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/zipline/uploads:/zipline/uploads
      - ${DOCKER_DIRECTORY}/appdata/zipline/public:/zipline/public
    labels:
      traefik.enable: true
      traefik.http.routers.zipline.rule: Host(`${ZIPELINE_SUBDOMAIN:-zipline}.${DOMAIN_NAME}`)
      traefik.http.routers.zipline.entrypoints: websecure
      traefik.http.routers.zipline.service: zipline
      traefik.http.services.zipline.loadbalancer.server.port: 3000

      homepage.group: Apps
      homepage.name: Zipline
      homepage.icon: https://raw.githubusercontent.com/diced/zipline/trunk/public/zipline.png
      homepage.href: https://${ZIPELINE_SUBDOMAIN:-zipline}.${DOMAIN_NAME}
      homepage.description: Screenshots and pastebins

  zipline-db:
  image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/zipline/db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      zipline:

networks:
  zipline:
    external: false
