#######################################
# SYNCTHING (syncing things)
#######################################

services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    profiles: ["syncthing", "apps", "all"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/syncthing/files:/data1
      - ${DOCKER_DIRECTORY}/apps/syncthing/config:/config
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.syncthing.rule: Host(`${SYNCTHING_SUBDOMAIN:-syncthing}.${DOMAIN_NAME}`)
      traefik.http.routers.syncthing.entrypoints: websecure
      traefik.http.routers.syncthing.service: syncthing
      traefik.http.services.syncthing.loadbalancer.server.port: 8384

      homepage.group: Apps
      homepage.name: Syncthing
      homepage.icon: syncthing.svg
      homepage.href: https://${SYNCTHING_SUBDOMAIN:-syncthing}.${DOMAIN_NAME}
      homepage.description: Syncs things
