####################################################################################
# FRESHRSS
####################################################################################

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/freshrss:/config
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.freshrss.rule: Host(`${FRESHRSS_SUBDOMAIN:-freshrss}.${DOMAIN_NAME}`)
      traefik.http.routers.freshrss.entrypoints: websecure
      traefik.http.routers.freshrss.service: freshrss
      traefik.http.services.freshrss.loadbalancer.server.port: 80

      homepage.group: Apps
      homepage.name: FreshRSS
      homepage.icon: freshrss.svg
      homepage.href: https://${FRESHRSS_SUBDOMAIN:-freshrss}.${DOMAIN_NAME}
      homepage.description: News Feed Reader
